<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Abhijits-MBP" failures="1" tests="10" name="Surefire test" time="17.275" errors="0" timestamp="2025-01-23T06:34:00 IST">
  <testcase classname="api.tests.UserTests" name="testCreateUser" time="2.534"/>
  <testcase classname="api.tests.UserTests" name="getUserByUserName" time="1.301"/>
  <testcase classname="api.tests.UserTests" name="updateUserByUserName" time="2.659"/>
  <testcase classname="api.tests.UserTests" name="deleteUser" time="1.361"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="1.274"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="1.534"/>
  <testcase classname="api.tests.DDTests" name="testPostUser" time="1.284"/>
  <testcase classname="api.tests.DDTests" name="deleteUserByUsername" time="1.454">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.tests.DDTests.deleteUserByUsername(DDTests.java:34)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 39 stack frames]]>
    </failure>
  </testcase> <!-- deleteUserByUsername -->
  <testcase classname="api.tests.DDTests" name="deleteUserByUsername" time="1.424"/>
  <testcase classname="api.tests.DDTests" name="deleteUserByUsername" time="1.342"/>
</testsuite> <!-- Surefire test -->
